# Imports

In [55]:
%pip install -q requirements.txt

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

In [ ]:
import yfinance as yf
import pandas as pd

# Constants

## Control

In [57]:
FETCH_DATA = False

## Routes

In [58]:
BITCOIN_DATA = 'bitcoin.csv'

## Dataset

In [59]:
TICKER = "BTC-USD"
START_DATE = "2024-10-01"
END_DATE = "2025-10-01"

## Indicator

In [60]:
THETA_ADX = 25
ADX_LOOKBACK = 14

# Functions

## Fetching data

In [61]:
def fetch_from_yfinance(ticker: str, route: str, start_date, end_date, fetch: bool=True):
    if fetch:
        df = yf.download(
            tickers=ticker,
            start=start_date,
            end=end_date
        )
        df.to_csv(route)
        df = pd.read_csv(route, skiprows=[1, 2], header=0)
        df = df.rename(columns={'Price': 'Date'})
        df = df.set_index('Date')
        df['Return'] = df['Close'].pct_change()
        df.to_csv(route)
    else:
        df = pd.read_csv(route)
    return df

# Fetch data

In [62]:
df = fetch_from_yfinance(TICKER, BITCOIN_DATA, START_DATE, END_DATE, FETCH_DATA)
df

,Date,Close,High,Low,Open,Volume,Return
0,2024-10-01,60837.007812,64110.980469,60189.277344,63335.605469,50220923500,NaN
1,2024-10-02,60632.785156,62357.687500,59996.949219,60836.324219,40762722398,-0.003357
2,2024-10-03,60759.402344,61469.039062,59878.804688,60632.484375,36106447279,0.002088
3,2024-10-04,62067.476562,62465.992188,60459.941406,60754.625000,29585472513,0.021529
4,2024-10-05,62089.949219,62371.023438,61689.582031,62067.609375,13305410749,0.000362
...,...,...,...,...,...,...,...
360,2025-09-26,109712.828125,110359.195312,108728.976562,109041.296875,57738288949,0.006085
361,2025-09-27,109681.945312,109778.500000,109144.296875,109707.140625,26308042910,-0.000281
362,2025-09-28,112122.640625,112375.484375,109236.945312,109681.945312,33371048505,0.022252
363,2025-09-29,114400.382812,114473.570312,111589.953125,112117.875000,60000147466,0.020315
364,2025-09-30,114056.085938,114836.617188,112740.562500,114396.523438,58986330258,-0.003010

# Preprocessing

# Indicators

## ADX

### Directional Moving (DM)

$$ +DM_t = H_{t} - H_{t-1} $$
$$ -DM_t = L_{t-1} - L_{t} $$

In [63]:
df['DMP'] = df['High'].diff()
df['DMN'] = df['Low'].diff()

def apply_dm_logic(row):
    dmp = row['DMP']
    dmn = row['DMN']
    
    dm_plus = dmp if dmp > 0 else 0
    dm_minus = -dmn if dmn < 0 else 0 
    
    if dm_plus > 0 and dm_minus > 0:
        if dm_plus > dm_minus:
            dm_minus = 0
        else:
            dm_plus = 0
            
    return pd.Series({'DM_Plus': dm_plus, 'DM_Minus': dm_minus})

dm_results = df.apply(apply_dm_logic, axis=1)

df['+DM'] = dm_results['DM_Plus']
df['-DM'] = dm_results['DM_Minus']

df = df.drop(columns=['DMP', 'DMN'])
df.head()

,Date,Close,High,Low,Open,Volume,Return,+DM,-DM
0,2024-10-01,60837.007812,64110.980469,60189.277344,63335.605469,50220923500,NaN,0.000000,0.000000
1,2024-10-02,60632.785156,62357.687500,59996.949219,60836.324219,40762722398,-0.003357,0.000000,192.328125
2,2024-10-03,60759.402344,61469.039062,59878.804688,60632.484375,36106447279,0.002088,0.000000,118.144531
3,2024-10-04,62067.476562,62465.992188,60459.941406,60754.625000,29585472513,0.021529,996.953125,0.000000
4,2024-10-05,62089.949219,62371.023438,61689.582031,62067.609375,13305410749,0.000362,0.000000,0.000000

### True Range (TR)

$$TR_{t} = max(H_{t}-L_{t}, |H_{t}-C_{t-1}|, |L_{t}-C_{t-1}|)$$

In [64]:
df['High_Low'] = df['High'] - df['Low']
df['High_PrevClose'] = abs(df['High'] - df['Close'].shift(1))
df['Low_PrevClose'] = abs(df['Low'] - df['Close'].shift(1))
df['TR'] = df[['High_Low', 'High_PrevClose', 'Low_PrevClose']].max(axis=1)


df = df.drop(columns=['High_Low', 'High_PrevClose', 'Low_PrevClose'])
df.head()

,Date,Close,High,Low,Open,Volume,Return,+DM,-DM,TR
0,2024-10-01,60837.007812,64110.980469,60189.277344,63335.605469,50220923500,NaN,0.000000,0.000000,3921.703125
1,2024-10-02,60632.785156,62357.687500,59996.949219,60836.324219,40762722398,-0.003357,0.000000,192.328125,2360.738281
2,2024-10-03,60759.402344,61469.039062,59878.804688,60632.484375,36106447279,0.002088,0.000000,118.144531,1590.234375
3,2024-10-04,62067.476562,62465.992188,60459.941406,60754.625000,29585472513,0.021529,996.953125,0.000000,2006.050781
4,2024-10-05,62089.949219,62371.023438,61689.582031,62067.609375,13305410749,0.000362,0.000000,0.000000,681.441406

### Average True Range (ATR)

$$ATR_{t} = \frac{1}{n} \sum_{i=t-n+1}^{t} TR_{i}$$

In [68]:
df['ATR'] = df['TR'].rolling(window=ADX_LOOKBACK).mean()
df.head(ADX_LOOKBACK)

,Date,Close,High,Low,Open,Volume,Return,+DM,-DM,TR,ATR
0,2024-10-01,60837.007812,64110.980469,60189.277344,63335.605469,50220923500,NaN,0.000000,0.000000,3921.703125,NaN
1,2024-10-02,60632.785156,62357.687500,59996.949219,60836.324219,40762722398,-0.003357,0.000000,192.328125,2360.738281,NaN
2,2024-10-03,60759.402344,61469.039062,59878.804688,60632.484375,36106447279,0.002088,0.000000,118.144531,1590.234375,NaN
3,2024-10-04,62067.476562,62465.992188,60459.941406,60754.625000,29585472513,0.021529,996.953125,0.000000,2006.050781,NaN
4,2024-10-05,62089.949219,62371.023438,61689.582031,62067.609375,13305410749,0.000362,0.000000,0.000000,681.441406,NaN
5,2024-10-06,62818.953125,62959.570312,61833.148438,62084.988281,14776233667,0.011741,588.546875,0.000000,1126.421875,NaN
6,2024-10-07,62236.660156,64443.707031,62152.550781,62819.109375,34253562610,-0.009269,1484.136719,0.000000,2291.156250,NaN
7,2024-10-08,62131.968750,63174.304688,61843.562500,62221.644531,28134475157,-0.001682,0.000000,308.988281,1330.742188,NaN
8,2024-10-09,60582.101562,62508.835938,60314.613281,62131.726562,27670982363,-0.024945,0.000000,1528.949219,2194.222656,NaN
9,2024-10-10,60274.500000,61236.722656,58895.207031,60581.929688,30452813570,-0.005077,0.000000,1419.406250,2341.515625,NaN
10,2024-10-11,62445.089844,63400.871094,60046.125000,60275.460938,30327141594,0.036012,2164.148438,0.000000,3354.746094,NaN
11,2024-10-12,63193.023438,63448.785156,62443.269531,62444.617188,16744110886,0.011977,47.914062,0.000000,1005.515625,NaN
12,2024-10-13,62851.375000,63272.652344,62035.636719,63192.945312,18177529690,-0.005406,0.000000,407.632812,1237.015625,NaN
13,2024-10-14,66046.125000,66482.492188,62442.152344,62848.398438,43706958056,0.050830,3209.839844,0.000000,4040.339844,2105.845982

### Simple Moving Average Directional Movement (SMA DM)

$$SMA+DM = \frac{1}{n} \sum_{i=t-n+1}^{t}+DM_{i}$$
$$SMA-DM = \frac{1}{n} \sum_{i=t-n+1}^{t}-DM_{i}$$

In [69]:
df['SMA+DM'] = df['+DM'].rolling(window=ADX_LOOKBACK).mean()
df['SMA-DM'] = df['-DM'].rolling(window=ADX_LOOKBACK).mean()

df.head(ADX_LOOKBACK)

,Date,Close,High,Low,Open,Volume,Return,+DM,-DM,TR,ATR,SMA+DM,SMA-DM
0,2024-10-01,60837.007812,64110.980469,60189.277344,63335.605469,50220923500,NaN,0.000000,0.000000,3921.703125,NaN,NaN,NaN
1,2024-10-02,60632.785156,62357.687500,59996.949219,60836.324219,40762722398,-0.003357,0.000000,192.328125,2360.738281,NaN,NaN,NaN
2,2024-10-03,60759.402344,61469.039062,59878.804688,60632.484375,36106447279,0.002088,0.000000,118.144531,1590.234375,NaN,NaN,NaN
3,2024-10-04,62067.476562,62465.992188,60459.941406,60754.625000,29585472513,0.021529,996.953125,0.000000,2006.050781,NaN,NaN,NaN
4,2024-10-05,62089.949219,62371.023438,61689.582031,62067.609375,13305410749,0.000362,0.000000,0.000000,681.441406,NaN,NaN,NaN
5,2024-10-06,62818.953125,62959.570312,61833.148438,62084.988281,14776233667,0.011741,588.546875,0.000000,1126.421875,NaN,NaN,NaN
6,2024-10-07,62236.660156,64443.707031,62152.550781,62819.109375,34253562610,-0.009269,1484.136719,0.000000,2291.156250,NaN,NaN,NaN
7,2024-10-08,62131.968750,63174.304688,61843.562500,62221.644531,28134475157,-0.001682,0.000000,308.988281,1330.742188,NaN,NaN,NaN
8,2024-10-09,60582.101562,62508.835938,60314.613281,62131.726562,27670982363,-0.024945,0.000000,1528.949219,2194.222656,NaN,NaN,NaN
9,2024-10-10,60274.500000,61236.722656,58895.207031,60581.929688,30452813570,-0.005077,0.000000,1419.406250,2341.515625,NaN,NaN,NaN
10,2024-10-11,62445.089844,63400.871094,60046.125000,60275.460938,30327141594,0.036012,2164.148438,0.000000,3354.746094,NaN,NaN,NaN
11,2024-10-12,63193.023438,63448.785156,62443.269531,62444.617188,16744110886,0.011977,47.914062,0.000000,1005.515625,NaN,NaN,NaN
12,2024-10-13,62851.375000,63272.652344,62035.636719,63192.945312,18177529690,-0.005406,0.000000,407.632812,1237.015625,NaN,NaN,NaN
13,2024-10-14,66046.125000,66482.492188,62442.152344,62848.398438,43706958056,0.050830,3209.839844,0.000000,4040.339844,2105.845982,606.538504,283.960658

### Directional Indicator (DI)

$$+DI_{t} = (\frac{SMA+DM_{t}}{ATR_{t}}) \times 100$$
$$-DI_{t} = (\frac{SMA-DM_{t}}{ATR_{t}}) \times 100$$

In [71]:
df['+DI'] = df['SMA+DM'] / df['ATR'] * 100
df['-DI'] = df['SMA-DM'] / df['ATR'] * 100
df.head(ADX_LOOKBACK)

,Date,Close,High,Low,Open,Volume,Return,+DM,-DM,TR,ATR,SMA+DM,SMA-DM,+DI,-DI
0,2024-10-01,60837.007812,64110.980469,60189.277344,63335.605469,50220923500,NaN,0.000000,0.000000,3921.703125,NaN,NaN,NaN,NaN,NaN
1,2024-10-02,60632.785156,62357.687500,59996.949219,60836.324219,40762722398,-0.003357,0.000000,192.328125,2360.738281,NaN,NaN,NaN,NaN,NaN
2,2024-10-03,60759.402344,61469.039062,59878.804688,60632.484375,36106447279,0.002088,0.000000,118.144531,1590.234375,NaN,NaN,NaN,NaN,NaN
3,2024-10-04,62067.476562,62465.992188,60459.941406,60754.625000,29585472513,0.021529,996.953125,0.000000,2006.050781,NaN,NaN,NaN,NaN,NaN
4,2024-10-05,62089.949219,62371.023438,61689.582031,62067.609375,13305410749,0.000362,0.000000,0.000000,681.441406,NaN,NaN,NaN,NaN,NaN
5,2024-10-06,62818.953125,62959.570312,61833.148438,62084.988281,14776233667,0.011741,588.546875,0.000000,1126.421875,NaN,NaN,NaN,NaN,NaN
6,2024-10-07,62236.660156,64443.707031,62152.550781,62819.109375,34253562610,-0.009269,1484.136719,0.000000,2291.156250,NaN,NaN,NaN,NaN,NaN
7,2024-10-08,62131.968750,63174.304688,61843.562500,62221.644531,28134475157,-0.001682,0.000000,308.988281,1330.742188,NaN,NaN,NaN,NaN,NaN
8,2024-10-09,60582.101562,62508.835938,60314.613281,62131.726562,27670982363,-0.024945,0.000000,1528.949219,2194.222656,NaN,NaN,NaN,NaN,NaN
9,2024-10-10,60274.500000,61236.722656,58895.207031,60581.929688,30452813570,-0.005077,0.000000,1419.406250,2341.515625,NaN,NaN,NaN,NaN,NaN
10,2024-10-11,62445.089844,63400.871094,60046.125000,60275.460938,30327141594,0.036012,2164.148438,0.000000,3354.746094,NaN,NaN,NaN,NaN,NaN
11,2024-10-12,63193.023438,63448.785156,62443.269531,62444.617188,16744110886,0.011977,47.914062,0.000000,1005.515625,NaN,NaN,NaN,NaN,NaN
12,2024-10-13,62851.375000,63272.652344,62035.636719,63192.945312,18177529690,-0.005406,0.000000,407.632812,1237.015625,NaN,NaN,NaN,NaN,NaN
13,2024-10-14,66046.125000,66482.492188,62442.152344,62848.398438,43706958056,0.050830,3209.839844,0.000000,4040.339844,2105.845982,606.538504,283.960658,28.802605,13.484398

### Directional Index (DX)

$$DX_{t} = \frac{|(+DI_{t})-(-DI_{t})|}{|(+DI_{t})+(-DI_{t})|} \times 100$$

In [72]:
df['DX'] = abs(df['+DI'] - df['-DI'])/abs(df['+DI'] + df['-DI']) * 100
df.head(ADX_LOOKBACK)

,Date,Close,High,Low,Open,Volume,Return,+DM,-DM,TR,ATR,SMA+DM,SMA-DM,+DI,-DI,DX
0,2024-10-01,60837.007812,64110.980469,60189.277344,63335.605469,50220923500,NaN,0.000000,0.000000,3921.703125,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-10-02,60632.785156,62357.687500,59996.949219,60836.324219,40762722398,-0.003357,0.000000,192.328125,2360.738281,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-10-03,60759.402344,61469.039062,59878.804688,60632.484375,36106447279,0.002088,0.000000,118.144531,1590.234375,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-10-04,62067.476562,62465.992188,60459.941406,60754.625000,29585472513,0.021529,996.953125,0.000000,2006.050781,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-10-05,62089.949219,62371.023438,61689.582031,62067.609375,13305410749,0.000362,0.000000,0.000000,681.441406,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-10-06,62818.953125,62959.570312,61833.148438,62084.988281,14776233667,0.011741,588.546875,0.000000,1126.421875,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-10-07,62236.660156,64443.707031,62152.550781,62819.109375,34253562610,-0.009269,1484.136719,0.000000,2291.156250,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-10-08,62131.968750,63174.304688,61843.562500,62221.644531,28134475157,-0.001682,0.000000,308.988281,1330.742188,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-10-09,60582.101562,62508.835938,60314.613281,62131.726562,27670982363,-0.024945,0.000000,1528.949219,2194.222656,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-10-10,60274.500000,61236.722656,58895.207031,60581.929688,30452813570,-0.005077,0.000000,1419.406250,2341.515625,NaN,NaN,NaN,NaN,NaN,NaN
10,2024-10-11,62445.089844,63400.871094,60046.125000,60275.460938,30327141594,0.036012,2164.148438,0.000000,3354.746094,NaN,NaN,NaN,NaN,NaN,NaN
11,2024-10-12,63193.023438,63448.785156,62443.269531,62444.617188,16744110886,0.011977,47.914062,0.000000,1005.515625,NaN,NaN,NaN,NaN,NaN,NaN
12,2024-10-13,62851.375000,63272.652344,62035.636719,63192.945312,18177529690,-0.005406,0.000000,407.632812,1237.015625,NaN,NaN,NaN,NaN,NaN,NaN
13,2024-10-14,66046.125000,66482.492188,62442.152344,62848.398438,43706958056,0.050830,3209.839844,0.000000,4040.339844,2105.845982,606.538504,283.960658,28.802605,13.484398,36.224385

### Average Directional Index (ADX)

$$ADX_{t} = \frac{1}{n} \sum_{i=t-n+1}^{t} DX_{i}$$

In [77]:
df['ADX'] = df['DX'].rolling(window=ADX_LOOKBACK).mean()
df.head(ADX_LOOKBACK*2 - 1)

,Date,Close,High,Low,Open,Volume,Return,+DM,-DM,TR,ATR,SMA+DM,SMA-DM,+DI,-DI,DX,ADX
0,2024-10-01,60837.007812,64110.980469,60189.277344,63335.605469,50220923500,NaN,0.000000,0.000000,3921.703125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-10-02,60632.785156,62357.687500,59996.949219,60836.324219,40762722398,-0.003357,0.000000,192.328125,2360.738281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-10-03,60759.402344,61469.039062,59878.804688,60632.484375,36106447279,0.002088,0.000000,118.144531,1590.234375,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-10-04,62067.476562,62465.992188,60459.941406,60754.625000,29585472513,0.021529,996.953125,0.000000,2006.050781,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-10-05,62089.949219,62371.023438,61689.582031,62067.609375,13305410749,0.000362,0.000000,0.000000,681.441406,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-10-06,62818.953125,62959.570312,61833.148438,62084.988281,14776233667,0.011741,588.546875,0.000000,1126.421875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-10-07,62236.660156,64443.707031,62152.550781,62819.109375,34253562610,-0.009269,1484.136719,0.000000,2291.156250,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-10-08,62131.968750,63174.304688,61843.562500,62221.644531,28134475157,-0.001682,0.000000,308.988281,1330.742188,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-10-09,60582.101562,62508.835938,60314.613281,62131.726562,27670982363,-0.024945,0.000000,1528.949219,2194.222656,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-10-10,60274.500000,61236.722656,58895.207031,60581.929688,30452813570,-0.005077,0.000000,1419.406250,2341.515625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2024-10-11,62445.089844,63400.871094,60046.125000,60275.460938,30327141594,0.036012,2164.148438,0.000000,3354.746094,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2024-10-12,63193.023438,63448.785156,62443.269531,62444.617188,16744110886,0.011977,47.914062,0.000000,1005.515625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024-10-13,62851.375000,63272.652344,62035.636719,63192.945312,18177529690,-0.005406,0.000000,407.632812,1237.015625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2024-10-14,66046.125000,66482.492188,62442.152344,62848.398438,43706958056,0.050830,3209.839844,0.000000,4040.339844,2105.845982,606.538504,283.960658,28.802605,13.484398,36.224385,NaN
14,2024-10-15,67041.109375,67881.679688,64809.195312,66050.367188,48863870879,0.015065,1399.187500,0.000000,3072.484375,2045.187500,706.480469,283.960658,34.543555,13.884334,42.659760,NaN
15,2024-10-16,67612.718750,68375.289062,66758.726562,67042.460938,38195189534,0.008526,493.609375,0.000000,1616.562500,1992.032087,741.738281,270.222935,37.235258,13.565190,46.594211,NaN
16,2024-10-17,67399.835938,67912.210938,66647.390625,67617.078125,32790898511,-0.003149,0.000000,111.335938,1264.820312,1968.788225,741.738281,269.736607,37.674864,13.700641,46.664695,NaN
17,2024-10-18,68418.789062,68969.750000,67177.820312,67419.109375,36857165014,0.015118,1057.539062,0.000000,1791.929688,1953.493862,746.065848,269.736607,38.191359,13.807907,46.891917,NaN
18,2024-10-19,68362.734375,68668.007812,68024.640625,68418.976562,14443497908,-0.000819,0.000000,0.000000,643.367188,1950.774275,746.065848,269.736607,38.244602,13.827156,46.891917,NaN
19,2024-10-20,69001.703125,69359.007812,68105.718750,68364.179688,18975847518,0.009347,691.000000,0.000000,1253.289062,1959.836217,753.383929,269.736607,38.441168,13.763222,47.271783,NaN
20,2024-10-21,67367.851562,69462.734375,66829.851562,69002.000000,37498611780,-0.023678,0.000000,1275.867188,2632.882812,1984.245257,647.374163,360.869978,32.625713,18.186763,28.416152,NaN
21,2024-10-22,67361.406250,67801.578125,66581.367188,67360.703125,31808472566,-0.000096,0.000000,248.484375,1220.210938,1976.350167,647.374163,356.548270,32.756046,18.040744,28.968960,NaN
22,2024-10-23,66432.195312,67402.742188,65188.035156,67362.375000,32263980353,-0.013794,0.000000,1393.332031,2214.707031,1977.813337,647.374163,346.861328,32.731813,17.537617,30.225519,NaN
23,2024-10-24,68161.054688,68798.960938,66454.101562,66653.703125,31414428647,0.026024,1396.218750,0.000000,2366.765625,1979.616908,747.104074,245.475167,37.739831,12.400135,50.537920,NaN
24,2024-10-25,66642.414062,68722.156250,65521.792969,68165.296875,41469984306,-0.022280,0.000000,932.308594,3200.363281,1968.589565,592.522042,312.068638,30.098810,15.852397,31.003349,NaN
25,2024-10-26,67014.695312,67317.921875,66360.593750,66628.734375,19588098156,0.005586,0.000000,0.000000,957.328125,1965.147600,589.099609,312.068638,29.977372,15.880163,30.741315,NaN
26,2024-10-27,67929.296875,68221.312500,66847.226562,67023.476562,16721307878,0.013648,903.390625,0.000000,1374.085938,1974.938337,653.627511,282.952009,33.096097,14.327131,39.577579,39.47639